// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { AuthProvider } from "./context/AuthContext";
// import Footer from "./components/Footer";
// import Navbar from "./components/Navbar";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// // export default function RootLayout({ children }) {
// //   return (
// //     <html lang="en">
// //       <body
// //         className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
// //       >
// //         <AuthProvider>
// //           <main className="flex-1">{children}</main>
// //           <Footer />  {/* ✅ globally accessible footer */}
// //           <Navbar />  {/* ✅ globally accessible navbar */}
// //         </AuthProvider>

// //       </body>
// //     </html>
// //   );
// // }

// app/layout.js
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import ApolloWrapper from "./lib/ApolloProvider"; // ✅ yaha import karo
import { AuthProvider } from "./context/AuthContext";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <ApolloWrapper>
            {/* ✅ ApolloProvider wrapper */}

            <Navbar />
            {children}
            <Footer />
          </ApolloWrapper>
        </AuthProvider>
      </body>
    </html>
  );
}
